import Parser from 'rss-parser';
import fs from 'fs';
import path from 'path';

const parser = new Parser();
const MEDIUM_USERNAME = 'vijayansabari06'; // Updated from user profile URL
const TARGET_TAG = 'blog'; 
const OUTPUT_FILE = path.join(process.cwd(), 'src/data/blogs.ts');

async function syncBlogs() {
  console.log(`Fetching Medium feed for @${MEDIUM_USERNAME}...`);
  
  try {
    const feed = await parser.parseURL(`https://medium.com/feed/@${MEDIUM_USERNAME}`);
    
    // Filter posts by tag
    const filteredPosts = feed.items.filter(item => {
      const categories = (item.categories || []).map(cat => cat.toLowerCase());
      return categories.includes(TARGET_TAG.toLowerCase());
    });

    console.log(`Found ${filteredPosts.length} posts matching tag "${TARGET_TAG}".`);

    let blogsMarkdown = `# SABARI VIJAYAN - AUTOMATED BLOG INDEX (MEDIUM)\n\n`;
    let blogList = [];

    filteredPosts.forEach(post => {
      // Extract featured image from content:encoded
      const content = post['content:encoded'] || '';
      const imgMatch = content.match(/<img[^>]+src="([^">]+)"/);
      const featuredImage = imgMatch ? imgMatch[1] : null;

      // Clean up snippet (remove HTML and limit length)
      let snippet = post.contentSnippet || '';
      if (!snippet && content) {
        // Simple HTML tag removal for a backup snippet
        snippet = content
          .replace(/<[^>]+>/g, ' ')
          .replace(/\s+/g, ' ')
          .trim()
          .substring(0, 200) + '...';
      } else if (snippet) {
        snippet = snippet.substring(0, 200).replace(/\n/g, ' ') + '...';
      } else {
        snippet = 'No snippet available.';
      }

      blogsMarkdown += `## ${post.title}\n`;
      blogsMarkdown += `- Published: ${post.pubDate}\n`;
      blogsMarkdown += `- Link: ${post.link}\n`;
      blogsMarkdown += `- Summary: ${snippet}\n\n`;

      blogList.push({
        title: post.title,
        link: post.link,
        date: post.pubDate,
        summary: snippet,
        image: featuredImage
      });
    });

    const fileContent = `
// THIS FILE IS AUTOMATICALLY GENERATED BY .github/workflows/update-portfolio.yml
// DO NOT EDIT MANUALLY.

export const blogList = ${JSON.stringify(blogList, null, 2)};

export const blogsData = \`
${blogsMarkdown}
Check out my full writing at [Medium](https://medium.com/@${MEDIUM_USERNAME}).
\`;
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent.trim());
    console.log(`Successfully updated ${OUTPUT_FILE} with ${filteredPosts.length} blogs.`);
  } catch (error) {
    console.error('Blog sync failed:', error);
    // Create an empty file if it fails so the import doesn't break
    if (!fs.existsSync(OUTPUT_FILE)) {
      fs.writeFileSync(OUTPUT_FILE, 'export const blogsData = "";');
    }
  }
}

syncBlogs();
