// THIS FILE IS AUTOMATICALLY GENERATED BY .github/workflows/update-portfolio.yml
// DO NOT EDIT MANUALLY.

export const blogList = [
  {
    "title": "Short Form content is killing you?",
    "link": "https://medium.com/@vijayansabari06/short-form-content-is-killing-you-5b63cef9fa60?source=rss-2c891f151b3f------2",
    "date": "Wed, 15 Apr 2026 08:07:50 GMT",
    "summary": "No snippet available."
  }
];

export const blogsData = `
# SABARI VIJAYAN - AUTOMATED BLOG INDEX (MEDIUM)

## Short Form content is killing you?
- Published: Wed, 15 Apr 2026 08:07:50 GMT
- Link: https://medium.com/@vijayansabari06/short-form-content-is-killing-you-5b63cef9fa60?source=rss-2c891f151b3f------2
- Summary: No snippet available.


Check out my full writing at [Medium](https://medium.com/@vijayansabari06).
`;