// THIS FILE IS AUTOMATICALLY GENERATED BY .github/workflows/update-projects.yml
// DO NOT EDIT MANUALLY.

export const repoMapping: Record<string, string> = {
  "umang-harmony-welfare-society-theme": "Sabari-Vijayan/Umang-Harmony-Welfare-Society-Theme",
  "skills-communicate-using-markdown": "Sabari-Vijayan/skills-communicate-using-markdown",
  "hsav": "Sabari-Vijayan/HSAV",
  "dotfiles": "Sabari-Vijayan/dotfiles",
  "mood_music": "Sabari-Vijayan/mood_music",
  "tinygoose": "Sabari-Vijayan/TinyGoose",
  "nointernetchallenge": "Sabari-Vijayan/NoInternetChallenge",
  "basicjava": "Sabari-Vijayan/BasicJava",
  "basicc": "Sabari-Vijayan/BasicC"
};

export const projectList = [
  {
    "id": 1,
    "title": "Umang-Harmony-Welfare-Society-Theme",
    "category": "PROJECT",
    "description": "Official website for Umang Harmony Welfare Society created using Ghost CMS",
    "link": "https://github.com/Sabari-Vijayan/Umang-Harmony-Welfare-Society-Theme",
    "date": "2026"
  },
  {
    "id": 2,
    "title": "skills-communicate-using-markdown",
    "category": "PROJECT",
    "description": "Exercise: Communicate using Markdown",
    "link": "https://github.com/Sabari-Vijayan/skills-communicate-using-markdown",
    "date": "2026"
  },
  {
    "id": 3,
    "title": "HSAV",
    "category": "PROJECT",
    "description": "Project V-Tile is a high-performance, open-source library of GEMM (General Matrix-Matrix Multiplication) kernels specifically optimized for the RISC-V Integrated Matrix Extension (IME) v0.6.",
    "link": "https://github.com/Sabari-Vijayan/HSAV",
    "date": "2026"
  },
  {
    "id": 4,
    "title": "dotfiles",
    "category": "PROJECT",
    "description": "These files include of the config files of my linux ricing setup. They mainky include the hyprland setup, nvim setup, and waybar setup etc excluding others.",
    "link": "https://github.com/Sabari-Vijayan/dotfiles",
    "date": "2025"
  },
  {
    "id": 5,
    "title": "mood_music",
    "category": "PROJECT",
    "description": "The project I made for a vibe coding themed hackathon in which some music is recommended to you based on your facial emotions",
    "link": "https://github.com/Sabari-Vijayan/mood_music",
    "date": "2025"
  },
  {
    "id": 6,
    "title": "TinyGoose",
    "category": "PROJECT",
    "description": "An Open source app for compressing, and resiving you images.",
    "link": "https://github.com/Sabari-Vijayan/TinyGoose",
    "date": "2025"
  },
  {
    "id": 7,
    "title": "NoInternetChallenge",
    "category": "PROJECT",
    "description": "The project I made for my Tinkerhub-No Internet Challenge.",
    "link": "https://github.com/Sabari-Vijayan/NoInternetChallenge",
    "date": "2025"
  },
  {
    "id": 8,
    "title": "BasicJava",
    "category": "PROJECT",
    "description": "Very basic level java programs",
    "link": "https://github.com/Sabari-Vijayan/BasicJava",
    "date": "2024"
  },
  {
    "id": 9,
    "title": "BasicC",
    "category": "PROJECT",
    "description": "Basic C programs :",
    "link": "https://github.com/Sabari-Vijayan/BasicC",
    "date": "2024"
  }
];

export const projectsData = `
# SABARI VIJAYAN - AUTOMATED PROJECT INDEX

## Umang-Harmony-Welfare-Society-Theme
- Description: Official website for Umang Harmony Welfare Society created using Ghost CMS
- Primary Language: CSS
- Stars: 2 | Forks: 2
- URL: https://github.com/Sabari-Vijayan/Umang-Harmony-Welfare-Society-Theme

## skills-communicate-using-markdown
- Description: Exercise: Communicate using Markdown
- Primary Language: Mixed
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/skills-communicate-using-markdown

## HSAV
- Description: Project V-Tile is a high-performance, open-source library of GEMM (General Matrix-Matrix Multiplication) kernels specifically optimized for the RISC-V Integrated Matrix Extension (IME) v0.6.
- Primary Language: Mixed
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/HSAV

## dotfiles
- Description: These files include of the config files of my linux ricing setup. They mainky include the hyprland setup, nvim setup, and waybar setup etc excluding others.
- Primary Language: Mixed
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/dotfiles

## mood_music
- Description: The project I made for a vibe coding themed hackathon in which some music is recommended to you based on your facial emotions
- Primary Language: HTML
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/mood_music

## TinyGoose
- Description: An Open source app for compressing, and resiving you images.
- Primary Language: CSS
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/TinyGoose

## NoInternetChallenge
- Description: The project I made for my Tinkerhub-No Internet Challenge.
- Primary Language: Mixed
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/NoInternetChallenge

## BasicJava
- Description: Very basic level java programs
- Primary Language: Java
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/BasicJava

## BasicC
- Description: Basic C programs :
- Primary Language: C
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/BasicC


Users can browse all projects on the [Portfolio Hub](/portfolio).
`;