// THIS FILE IS AUTOMATICALLY GENERATED BY .github/workflows/update-projects.yml
// DO NOT EDIT MANUALLY.

export const repoMapping: Record<string, string> = {
  "tinkerfetch": "Sabari-Vijayan/tinkerfetch",
  "portfolio": "Sabari-Vijayan/Portfolio",
  "rit_tracker": "Sabari-Vijayan/RIT_TRACKER",
  "code-a-pooakalam-25": "Sabari-Vijayan/code-a-pooakalam-25",
  "umang-harmony-welfare-society-theme": "Sabari-Vijayan/Umang-Harmony-Welfare-Society-Theme",
  "dynamic-pricing-ui": "Sabari-Vijayan/Dynamic-Pricing-UI",
  "neurobots-hackathon-2026": "Sabari-Vijayan/neurobots-hackathon-2026",
  "cartinder": "Sabari-Vijayan/cartinder",
  "voiceform": "Sabari-Vijayan/VoiceForm"
};

export const projectList = [
  {
    "id": 1,
    "title": "tinkerfetch",
    "category": "PROJECT",
    "description": "Tinkerfetch is a terminal-based \"TinkerHub\" themed system information tool. It's a custom-designed \"skin\" for the Fastfetch engine, featuring a dedicated mode to track upcoming community events.",
    "link": "https://github.com/Sabari-Vijayan/tinkerfetch",
    "date": "2026",
    "stars": 18
  },
  {
    "id": 2,
    "title": "Portfolio",
    "category": "PROJECT",
    "description": "A personal showcase built with React, integrated with an AI assistant to answer all your questions about my work instantly.",
    "link": "https://github.com/Sabari-Vijayan/Portfolio",
    "date": "2026",
    "stars": 3
  },
  {
    "id": 3,
    "title": "RIT_TRACKER",
    "category": "PROJECT",
    "description": "RIT Tracker is a web-based navigation tool designed to help students, visitors, and faculty easily locate buildings, classrooms, and facilities within our campus. It features an interactive 3D AR view, allowing users to explore campus buildings in detail.",
    "link": "https://github.com/Sabari-Vijayan/RIT_TRACKER",
    "date": "2026",
    "stars": 2
  },
  {
    "id": 4,
    "title": "code-a-pooakalam-25",
    "category": "PROJECT",
    "description": "Official website for code-a-pookalam 2025 by TinkerHub RIT",
    "link": "https://github.com/Sabari-Vijayan/code-a-pooakalam-25",
    "date": "2026",
    "stars": 2
  },
  {
    "id": 5,
    "title": "Umang-Harmony-Welfare-Society-Theme",
    "category": "PROJECT",
    "description": "Official website for Umang Harmony Welfare Society created using Ghost CMS",
    "link": "https://github.com/Sabari-Vijayan/Umang-Harmony-Welfare-Society-Theme",
    "date": "2026",
    "stars": 2
  },
  {
    "id": 6,
    "title": "Dynamic-Pricing-UI",
    "category": "PROJECT",
    "description": "A dynamic pricing interface built with Angular and Signals to efficiently parse and display complex, nested JSON data.",
    "link": "https://github.com/Sabari-Vijayan/Dynamic-Pricing-UI",
    "date": "2026",
    "stars": 0
  },
  {
    "id": 7,
    "title": "neurobots-hackathon-2026",
    "category": "PROJECT",
    "description": "An AI-powered system to detect cheating behavior in online exams using Isolation Forest algorithm.",
    "link": "https://github.com/Sabari-Vijayan/neurobots-hackathon-2026",
    "date": "2026",
    "stars": 0
  },
  {
    "id": 8,
    "title": "cartinder",
    "category": "PROJECT",
    "description": "CarTinder is a modern, full-stack car rental platform with a \"Tinder-style\" swiping experience. Users can swipe through available cars, like their favorites, chat with dealers, and book rides—all in a sleek, responsive interface.",
    "link": "https://github.com/Sabari-Vijayan/cartinder",
    "date": "2026",
    "stars": 0
  },
  {
    "id": 9,
    "title": "VoiceForm",
    "category": "PROJECT",
    "description": "A multilingual voice interface that uses LLMs to conduct natural interviews and transform raw speech into structured, actionable data.",
    "link": "https://github.com/Sabari-Vijayan/VoiceForm",
    "date": "2026",
    "stars": 0
  }
];

export const projectsData = `
# SABARI VIJAYAN - AUTOMATED PROJECT INDEX

## tinkerfetch
- Description: Tinkerfetch is a terminal-based "TinkerHub" themed system information tool. It's a custom-designed "skin" for the Fastfetch engine, featuring a dedicated mode to track upcoming community events.
- Primary Language: Shell
- Stars: 18 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/tinkerfetch

## Portfolio
- Description: A personal showcase built with React, integrated with an AI assistant to answer all your questions about my work instantly.
- Primary Language: TypeScript
- Stars: 3 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/Portfolio
- Live Site: https://portfolio-liard-alpha-anenqdv7wr.vercel.app

## RIT_TRACKER
- Description: RIT Tracker is a web-based navigation tool designed to help students, visitors, and faculty easily locate buildings, classrooms, and facilities within our campus. It features an interactive 3D AR view, allowing users to explore campus buildings in detail.
- Primary Language: HTML
- Stars: 2 | Forks: 3
- URL: https://github.com/Sabari-Vijayan/RIT_TRACKER

## code-a-pooakalam-25
- Description: Official website for code-a-pookalam 2025 by TinkerHub RIT
- Primary Language: HTML
- Stars: 2 | Forks: 1
- URL: https://github.com/Sabari-Vijayan/code-a-pooakalam-25

## Umang-Harmony-Welfare-Society-Theme
- Description: Official website for Umang Harmony Welfare Society created using Ghost CMS
- Primary Language: CSS
- Stars: 2 | Forks: 2
- URL: https://github.com/Sabari-Vijayan/Umang-Harmony-Welfare-Society-Theme

## Dynamic-Pricing-UI
- Description: A dynamic pricing interface built with Angular and Signals to efficiently parse and display complex, nested JSON data.
- Primary Language: TypeScript
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/Dynamic-Pricing-UI
- Live Site: https://dynamic-pricing-ui-alpha.vercel.app

## neurobots-hackathon-2026
- Description: An AI-powered system to detect cheating behavior in online exams using Isolation Forest algorithm.
- Primary Language: JavaScript
- Stars: 0 | Forks: 3
- URL: https://github.com/Sabari-Vijayan/neurobots-hackathon-2026

## cartinder
- Description: CarTinder is a modern, full-stack car rental platform with a "Tinder-style" swiping experience. Users can swipe through available cars, like their favorites, chat with dealers, and book rides—all in a sleek, responsive interface.
- Primary Language: TypeScript
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/cartinder
- Live Site: https://cartinder-dun.vercel.app

## VoiceForm
- Description: A multilingual voice interface that uses LLMs to conduct natural interviews and transform raw speech into structured, actionable data.
- Primary Language: JavaScript
- Stars: 0 | Forks: 0
- URL: https://github.com/Sabari-Vijayan/VoiceForm


Users can browse all projects on the [Portfolio Hub](/portfolio).
`;